# -*- coding: utf-8 -*-
"""automate Anisa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fGZ0a53ba7p2HJuCcvjZLLWhc7uAGp5S
"""

import pandas as pd
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('heart.csv')

print("Dataset berhasil dimuat")
print(df.head())

print("\nMissing Value:")
print(df.isnull().sum())

print("\nJumlah data duplikat sebelum dihapus:")
print(df.duplicated().sum())

df.drop_duplicates(inplace=True)

print("\nJumlah data duplikat setelah dihapus:")
print(df.duplicated().sum())

X = df.drop('target', axis=1)
y = df['target']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

output_folder = 'dataset_preprocessing'

if not os.path.exists(output_folder):
    os.makedirs(output_folder)

pd.DataFrame(X_train).to_csv(
    f'{output_folder}/X_train.csv',
    index=False
)

pd.DataFrame(X_test).to_csv(
    f'{output_folder}/X_test.csv',
    index=False
)

y_train.to_csv(
    f'{output_folder}/y_train.csv',
    index=False
)

y_test.to_csv(
    f'{output_folder}/y_test.csv',
    index=False
)

print("\nPreprocessing selesai!")
print("Dataset berhasil disimpan di folder dataset_preprocessing")